//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProlabProje3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Groups = new HashSet<Group>();
            this.Students = new HashSet<Student>();
            this.AcedemicMembers = new HashSet<AcedemicMember>();
            this.Lessons = new HashSet<Lesson>();
        }
    
        public int DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> FacultyId { get; set; }
        public string DepartmentCode { get; set; }
    
        public virtual Faculty Faculty { get; set; }
        public virtual ICollection<Group> Groups { get; set; }
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<AcedemicMember> AcedemicMembers { get; set; }
        public virtual ICollection<Lesson> Lessons { get; set; }
    }
}
