//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProlabProje3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.StudentLessons = new HashSet<StudentLesson>();
        }
    
        public Nullable<int> AcedemicMemberId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public int GroupId { get; set; }
        public Nullable<int> LessonId { get; set; }
    
        public virtual AcedemicMember AcedemicMember { get; set; }
        public virtual Department Department { get; set; }
        public virtual Lesson Lesson { get; set; }
        public virtual ICollection<StudentLesson> StudentLessons { get; set; }
    }
}
