//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProlabProje3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        public Lesson()
        {
            this.AcedemicMembers = new HashSet<AcedemicMember>();
            this.Departments = new HashSet<Department>();
            this.Groups = new HashSet<Group>();
        }
    
        public int LessonId { get; set; }
        public string LessonName { get; set; }
        public string LessonCode { get; set; }
    
        public virtual ICollection<AcedemicMember> AcedemicMembers { get; set; }
        public virtual ICollection<Department> Departments { get; set; }
        public virtual ICollection<Group> Groups { get; set; }
    }
}
