//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProlabProje3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int StudentLessonId { get; set; }
        public Nullable<int> Vize1 { get; set; }
        public Nullable<int> Vize2 { get; set; }
        public Nullable<int> Final { get; set; }
    
        public virtual StudentLesson StudentLesson { get; set; }
    }
}
